import React from 'react';
import type { NavItem, Translations, Language } from './types';

// SVG Icon Components
const HomeIcon = ({ className }: { className?: string }) => (
  <svg className={className} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8h5z" /></svg>
);
const NotesIcon = ({ className }: { className?: string }) => (
  <svg className={className} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M14 2H6c-1.1 0-1.99.9-1.99 2L4 20c0 1.1.89 2 1.99 2H18c1.1 0 2-.9 2-2V8l-6-6zm2 16H8v-2h8v2zm0-4H8v-2h8v2zm-3-5V3.5L18.5 9H13z" /></svg>
);
const QuizIcon = ({ className }: { className?: string }) => (
  <svg className={className} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm2.07-7.75l-.9.92C13.45 10.89 13 11.5 13 12.5h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z" /></svg>
);
const ChatIcon = ({ className }: { className?: string }) => (
  <svg className={className} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M20 2H4c-1.1 0-2 .9-2 2v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-2 12H6v-2h12v2zm0-3H6V9h12v2zm0-3H6V6h12v2z" /></svg>
);
const QnAIcon = ({ className }: { className?: string }) => (
  <svg className={className} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M11 18h2v-2h-2v2zm1-16C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm0-14c-2.21 0-4 1.79-4 4h2c0-1.1.9-2 2-2s2 .9 2 2c0 2-3 1.75-3 5h2c0-2.25 3-2.5 3-5 0-2.21-1.79-4-4-4z" /></svg>
);
const ProfileIcon = ({ className }: { className?: string }) => (
  <svg className={className} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z" /></svg>
);


export const NAV_ITEMS: NavItem[] = [
  { id: 'home', label: 'home', icon: HomeIcon },
  { id: 'notes', label: 'notes', icon: NotesIcon },
  { id: 'quiz', label: 'quiz', icon: QuizIcon },
  { id: 'chat', label: 'ai_chat', icon: ChatIcon },
  { id: 'qna', label: 'qna', icon: QnAIcon },
  { id: 'profile', label: 'profile', icon: ProfileIcon },
];

export const translations: Record<Language, Translations> = {
  en: {
    home: 'Home',
    notes: 'Notes',
    quiz: 'Quiz',
    ai_chat: 'AI Chat',
    qna: 'QnA',
    profile: 'Profile',
    welcome_back: 'Welcome Back,',
    whats_on_your_mind: "What's on your mind today?",
    generate_notes: 'Generate Notes',
    enter_topic: 'Enter a topic, or upload an image',
    generating_notes_message: 'Our AI is crafting your notes... Please wait.',
    notes_for_topic: 'Notes for',
    quiz_practice: 'Quiz Practice',
    generate_quiz: 'Generate Quiz',
    enter_quiz_topic: 'Enter a topic, or upload an image',
    generating_quiz_message: 'Our AI is preparing your quiz... Good luck!',
    quiz_on_topic: 'Quiz on',
    ai_doubt_solver: 'AI Doubt Solver',
    ask_anything: 'Ask me anything about your subjects...',
    sending: 'Sending...',
    my_progress: 'My Progress',
    overall_accuracy: 'Overall Accuracy',
    quizzes_completed: 'Quizzes Completed',
    weekly_performance: 'Weekly Performance',
    language: 'Language',
    english: 'English',
    hindi: 'हिंदी',
    hinglish: 'Hinglish',
    submit: 'Submit',
    next_question: 'Next Question',
    correct_answer: 'Correct!',
    wrong_answer: 'Incorrect!',
    your_answer: 'Your answer',
    quiz_complete: 'Quiz Complete!',
    your_score: 'Your Score',
    play_again: 'Play Again',
    select_language: 'Select Language',
    ai_is_typing: 'AI is typing...',
    get_started_notes: 'Generate instant notes on any topic.',
    get_started_quiz: 'Test your knowledge with AI quizzes.',
    get_started_chat: 'Get your doubts cleared instantly.',
    quick_actions: 'Quick Actions',
    name: 'Name',
    class_stream: 'Class/Stream',
    start_learning: 'Start Learning',
    qna_header: 'QnA Section',
    qna_placeholder: 'Ask any question... numerical or theoretical',
    get_solution: 'Get Solution',
    or_upload_image: 'or upload an image of the question',
    generating_solution_message: 'Our AI is solving your question...',
    solution_for_question: 'Solution',
    capture_image: 'Capture Image',
    retake_photo: 'Retake',
    use_photo: 'Use Photo',
  },
  hi: {
    home: 'होम',
    notes: 'नोट्स',
    quiz: 'क्विज़',
    ai_chat: 'AI चैट',
    qna: 'प्रश्न-उत्तर',
    profile: 'प्रोफ़ाइल',
    welcome_back: 'वापसी पर स्वागत है,',
    whats_on_your_mind: 'आज आपके मन में क्या है?',
    generate_notes: 'नोट्स बनाएं',
    enter_topic: 'एक विषय दर्ज करें, या एक छवि अपलोड करें',
    generating_notes_message: 'हमारा AI आपके नोट्स तैयार कर रहा है... कृपया प्रतीक्षा करें।',
    notes_for_topic: 'के लिए नोट्स',
    quiz_practice: 'क्विज़ अभ्यास',
    generate_quiz: 'क्विज़ बनाएं',
    enter_quiz_topic: 'एक विषय दर्ज करें, या एक छवि अपलोड करें',
    generating_quiz_message: 'हमारा AI आपकी क्विज़ तैयार कर रहा है... शुभकामनाएँ!',
    quiz_on_topic: 'पर क्विज़',
    ai_doubt_solver: 'AI संदेह निवारक',
    ask_anything: 'अपने विषयों के बारे में कुछ भी पूछें...',
    sending: 'भेज रहा है...',
    my_progress: 'मेरी प्रगति',
    overall_accuracy: 'कुल सटीकता',
    quizzes_completed: 'पूरी की गई क्विज़',
    weekly_performance: 'साप्ताहिक प्रदर्शन',
    language: 'भाषा',
    english: 'English',
    hindi: 'हिंदी',
    hinglish: 'Hinglish',
    submit: 'सबमिट करें',
    next_question: 'अगला प्रश्न',
    correct_answer: 'सही!',
    wrong_answer: 'गलत!',
    your_answer: 'आपका जवाब',
    quiz_complete: 'क्विज़ पूरी हुई!',
    your_score: 'आपका स्कोर',
    play_again: 'फिर से खेलें',
    select_language: 'भाषा चुनें',
    ai_is_typing: 'AI टाइप कर रहा है...',
    get_started_notes: 'किसी भी विषय पर तुरंत नोट्स बनाएं।',
    get_started_quiz: 'AI क्विज़ के साथ अपने ज्ञान का परीक्षण करें।',
    get_started_chat: 'अपनी शंकाओं का तुरंत समाधान पाएं।',
    quick_actions: 'त्वरित कार्रवाइयां',
    name: 'नाम',
    class_stream: 'कक्षा/स्ट्रीम',
    start_learning: 'सीखना शुरू करें',
    qna_header: 'प्रश्न-उत्तर खंड',
    qna_placeholder: 'कोई भी प्रश्न पूछें... संख्यात्मक या सैद्धांतिक',
    get_solution: 'उत्तर प्राप्त करें',
    or_upload_image: 'या प्रश्न की एक छवि अपलोड करें',
    generating_solution_message: 'हमारा AI आपके प्रश्न का समाधान कर रहा है...',
    solution_for_question: 'समाधान',
    capture_image: 'छवि कैप्चर करें',
    retake_photo: 'फिर से लें',
    use_photo: 'फोटो का उपयोग करें',
  },
  hn: {
    home: 'Home',
    notes: 'Notes',
    quiz: 'Quiz',
    ai_chat: 'AI Chat',
    qna: 'QnA',
    profile: 'Profile',
    welcome_back: 'Welcome Vaapas,',
    whats_on_your_mind: 'Aaj aapke man mein kya hai?',
    generate_notes: 'Notes Banao',
    enter_topic: 'Ek topic daalein, ya ek image upload karein',
    generating_notes_message: 'Hamara AI aapke notes bana raha hai... Thoda intezaar karein.',
    notes_for_topic: 'ke liye notes',
    quiz_practice: 'Quiz Practice',
    generate_quiz: 'Quiz Banao',
    enter_quiz_topic: 'Ek topic daalein, ya ek image upload karein',
    generating_quiz_message: 'Hamara AI aapka quiz taiyaar kar raha hai... Good luck!',
    quiz_on_topic: 'par Quiz',
    ai_doubt_solver: 'AI Doubt Solver',
    ask_anything: 'Apne subjects ke baare mein kuch bhi pucho...',
    sending: 'Bhej raha hai...',
    my_progress: 'Meri Progress',
    overall_accuracy: 'Overall Accuracy',
    quizzes_completed: 'Quizzes Poori Huin',
    weekly_performance: 'Hafte ka Performance',
    language: 'Bhasha',
    english: 'English',
    hindi: 'हिंदी',
    hinglish: 'Hinglish',
    submit: 'Submit Karein',
    next_question: 'Agla Sawaal',
    correct_answer: 'Sahi!',
    wrong_answer: 'Galat!',
    your_answer: 'Aapka jawaab',
    quiz_complete: 'Quiz Poora Hua!',
    your_score: 'Aapka Score',
    play_again: 'Phir se Khelo',
    select_language: 'Bhasha Chuno',
    ai_is_typing: 'AI type kar raha hai...',
    get_started_notes: 'Kisi bhi topic par turant notes banayein.',
    get_started_quiz: 'AI quizzes ke saath apne knowledge ko test karein.',
    get_started_chat: 'Apne doubts turant clear karein.',
    quick_actions: 'Quick Actions',
    name: 'Naam',
    class_stream: 'Class/Stream',
    start_learning: 'Seekhna Shuru Karein',
    qna_header: 'QnA Section',
    qna_placeholder: 'Koi bhi sawaal pucho... numerical ya theoretical',
    get_solution: 'Solution Paayein',
    or_upload_image: 'ya sawaal ka image upload karein',
    generating_solution_message: 'Hamara AI aapka sawaal solve kar raha hai...',
    solution_for_question: 'Solution',
    capture_image: 'Image Capture Karein',
    retake_photo: 'Dobara lein',
    use_photo: 'Photo Use Karein',
  },
};